-- MODULO ADMINISTRACION

CREATE TABLE IF NOT EXISTS personal (
  id_pers       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom           VARCHAR(60)  NOT NULL,
  ape_pat       VARCHAR(60)  NOT NULL,
  ape_mat       VARCHAR(60),
  ci            VARCHAR(20),
  profesion     VARCHAR(60),
  ocupacion     VARCHAR(60),
  fecha_naci    DATE,
  sexo          CHAR(1)      CHECK (sexo IN ('M','F')),
  email         VARCHAR(120),
  estado        BOOLEAN       DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS rol (
  id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) UNIQUE NOT NULL,
  descripcion VARCHAR(200),
  estado BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS usuario (
  id_usr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pers INTEGER NOT NULL,
  login VARCHAR(40) UNIQUE NOT NULL,
  pass_hash VARCHAR(200) NOT NULL,
  estado BOOLEAN DEFAULT TRUE,
  CONSTRAINT fk_usuario_personal FOREIGN KEY (id_pers)
    REFERENCES personal(id_pers) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS usuario_rol (
  id_usr INTEGER NOT NULL,
  id_rol INTEGER NOT NULL,
  fecha_asig TIMESTAMP DEFAULT now(),
  PRIMARY KEY (id_usr, id_rol),
  CONSTRAINT fk_ur_usuario FOREIGN KEY (id_usr) REFERENCES usuario(id_usr),
  CONSTRAINT fk_ur_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

CREATE TABLE IF NOT EXISTS domicilio (
  id_dom        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pers       INTEGER NOT NULL,
  calle_resid   VARCHAR(120),
  numero        VARCHAR(15),
  zona          VARCHAR(60),
  tipo_dom      VARCHAR(30),
  CONSTRAINT fk_dom_personal
    FOREIGN KEY (id_pers) REFERENCES personal(id_pers)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fonos (
  id_fono       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pers       INTEGER NOT NULL,
  fono_princ    VARCHAR(30),
  celular       VARCHAR(30),
  fono_vecino   VARCHAR(30),
  fono_trab     VARCHAR(30),
  CONSTRAINT fk_fono_personal
    FOREIGN KEY (id_pers) REFERENCES personal(id_pers)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS horario_atencion (
  id_horario    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pers       INTEGER NOT NULL,
  dia_semana    SMALLINT NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  hora_ini      TIME      NOT NULL,
  hora_fin      TIME      NOT NULL,
  observacion   VARCHAR(150),
  CONSTRAINT ck_horario_rango CHECK (hora_fin > hora_ini),
  CONSTRAINT fk_horario_personal
    FOREIGN KEY (id_pers) REFERENCES personal(id_pers)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS menu_item (
  id_menu       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(60)  NOT NULL,
  ruta          VARCHAR(120),
  orden         INTEGER      DEFAULT 0,
  estado        BOOLEAN      DEFAULT TRUE,
  id_padre      INTEGER,
  CONSTRAINT fk_menu_padre
    FOREIGN KEY (id_padre) REFERENCES menu_item(id_menu)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS rol_menu (
  id_rol        INTEGER NOT NULL,
  id_menu       INTEGER NOT NULL,
  puede_ver     BOOLEAN DEFAULT TRUE,
  puede_crear   BOOLEAN DEFAULT FALSE,
  puede_editar  BOOLEAN DEFAULT FALSE,
  puede_borrar  BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (id_rol, id_menu),
  CONSTRAINT fk_rm_rol  FOREIGN KEY (id_rol)  REFERENCES rol(id_rol)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_rm_menu FOREIGN KEY (id_menu) REFERENCES menu_item(id_menu)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_personal_apellidos ON personal(ape_pat, ape_mat, nom);
CREATE INDEX IF NOT EXISTS ix_horario_pers_dia   ON horario_atencion(id_pers, dia_semana);
CREATE INDEX IF NOT EXISTS ix_usuario_login      ON usuario(login);


-- MODULO CLINICO

CREATE TABLE IF NOT EXISTS persona (
  id_per        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom           VARCHAR(60)  NOT NULL,
  ape_pat       VARCHAR(60)  NOT NULL,
  ape_mat       VARCHAR(60),
  ci            VARCHAR(20),
  sexo          CHAR(1)      CHECK (sexo IN ('M','F')),
  fecha_naci    DATE,
  email         VARCHAR(120),
  procedencia   VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS domicilio_per (
  id_dom        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_per        INTEGER NOT NULL,
  calle_resid   VARCHAR(120),
  numero        VARCHAR(15),
  zona          VARCHAR(60),
  tipo_dom      VARCHAR(30),
  CONSTRAINT fk_domper_persona
    FOREIGN KEY (id_per) REFERENCES persona(id_per)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fono_per (
  id_fono       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_per        INTEGER NOT NULL,
  fono_princ    VARCHAR(30),
  celular       VARCHAR(30),
  fono_vecino   VARCHAR(30),
  fono_trab     VARCHAR(30),
  CONSTRAINT fk_fonoper_persona
    FOREIGN KEY (id_per) REFERENCES persona(id_per)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS donante (
  id_don        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_per        INTEGER NOT NULL UNIQUE,
  cod_don       VARCHAR(15) UNIQUE,
  grupo_sang    VARCHAR(3),
  rh            VARCHAR(2),
  tipo_donante  VARCHAR(30),
  estado        VARCHAR(15) DEFAULT 'ACTIVO',
  CONSTRAINT fk_donante_persona
    FOREIGN KEY (id_per) REFERENCES persona(id_per)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS admision (
  id_adm        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_don        INTEGER NOT NULL,
  fecha_hora    TIMESTAMP NOT NULL DEFAULT now(),
  usuario_reg   VARCHAR(60),
  observacion   VARCHAR(250),
  CONSTRAINT fk_adm_don
    FOREIGN KEY (id_don) REFERENCES donante(id_don)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS tamizaje_medico (
  id_tam        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_adm        INTEGER NOT NULL UNIQUE,
  cuestionario  JSONB,
  criterios_ok  BOOLEAN,
  apto_pre      BOOLEAN,
  observacion   VARCHAR(250),
  CONSTRAINT fk_tam_adm
    FOREIGN KEY (id_adm) REFERENCES admision(id_adm)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS examen_fisico (
  id_fis        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_adm        INTEGER NOT NULL UNIQUE,
  tension       VARCHAR(15),
  pulso         SMALLINT,
  temperatura   NUMERIC(4,1),
  talla_cm      NUMERIC(5,2),
  peso_kg       NUMERIC(5,2),
  apto          BOOLEAN,
  observacion   VARCHAR(250),
  CONSTRAINT fk_fis_adm
    FOREIGN KEY (id_adm) REFERENCES admision(id_adm)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS extraccion (
  id_ext        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_adm        INTEGER NOT NULL,
  fecha_hora    TIMESTAMP NOT NULL DEFAULT now(),
  bolsa_cod     VARCHAR(30) UNIQUE,
  volumen_ml    SMALLINT,
  estado        VARCHAR(15) NOT NULL DEFAULT 'VALIDA',
  CONSTRAINT fk_ext_adm
    FOREIGN KEY (id_adm) REFERENCES admision(id_adm)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_persona_ci         ON persona(ci);
CREATE INDEX IF NOT EXISTS ix_persona_apellidos  ON persona(ape_pat, ape_mat, nom);
CREATE INDEX IF NOT EXISTS ix_domper_idper       ON domicilio_per(id_per);
CREATE INDEX IF NOT EXISTS ix_fonoper_idper      ON fono_per(id_per);
CREATE INDEX IF NOT EXISTS ix_donante_idper      ON donante(id_per);
CREATE INDEX IF NOT EXISTS ix_adm_iddon_fh       ON admision(id_don, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS ix_tam_idadm          ON tamizaje_medico(id_adm);
CREATE INDEX IF NOT EXISTS ix_fis_idadm          ON examen_fisico(id_adm);
CREATE INDEX IF NOT EXISTS ix_ext_idadm_fh       ON extraccion(id_adm, fecha_hora DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ext_bolsa   ON extraccion(bolsa_cod);


-- MODULO 3 LABORATORIO

CREATE TABLE IF NOT EXISTS tipo_prueba (
  id_tipoprueba INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(60) UNIQUE NOT NULL,
  descripcion   VARCHAR(200),
  activo        BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS prueba_lab (
  id_prueba     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ext        INTEGER NOT NULL,
  id_tipoprueba INTEGER NOT NULL,
  fecha_hora    TIMESTAMP NOT NULL DEFAULT now(),
  realizado_por INTEGER,
  estado        VARCHAR(15) DEFAULT 'PENDIENTE',
  observacion   VARCHAR(200),
  CONSTRAINT fk_prueba_ext FOREIGN KEY (id_ext)
    REFERENCES extraccion(id_ext)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_prueba_tipo FOREIGN KEY (id_tipoprueba)
    REFERENCES tipo_prueba(id_tipoprueba)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS resultado_lab (
  id_result     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_prueba     INTEGER NOT NULL UNIQUE,
  resultado     VARCHAR(120),
  detalle       JSONB,
  validado      BOOLEAN DEFAULT FALSE,
  validado_por  INTEGER,
  validado_en   TIMESTAMP,
  CONSTRAINT fk_result_prueba FOREIGN KEY (id_prueba)
    REFERENCES prueba_lab(id_prueba)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS control_calidad_lab (
  id_cc         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_prueba     INTEGER NOT NULL,
  parametro     VARCHAR(60) NOT NULL,
  valor         VARCHAR(60),
  conforme      BOOLEAN,
  fecha_control TIMESTAMP DEFAULT now(),
  CONSTRAINT fk_cc_prueba FOREIGN KEY (id_prueba)
    REFERENCES prueba_lab(id_prueba)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS validacion_lab (
  id_validacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_result     INTEGER NOT NULL,
  id_personal   INTEGER,
  fecha_val     TIMESTAMP DEFAULT now(),
  observacion   VARCHAR(250),
  estado        VARCHAR(20) DEFAULT 'VALIDADO',
  CONSTRAINT fk_valid_result FOREIGN KEY (id_result)
    REFERENCES resultado_lab(id_result)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_valid_personal FOREIGN KEY (id_personal)
    REFERENCES personal(id_pers)
      ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_prueba_ext         ON prueba_lab(id_ext);
CREATE INDEX IF NOT EXISTS ix_prueba_tipo        ON prueba_lab(id_tipoprueba);
CREATE INDEX IF NOT EXISTS ix_result_validado    ON resultado_lab(validado);
CREATE INDEX IF NOT EXISTS ix_validacion_result  ON validacion_lab(id_result);
CREATE INDEX IF NOT EXISTS ix_cc_prueba          ON control_calidad_lab(id_prueba);


-- MODULO 4 PRODUCCION / CONTROL DE CALIDAD / DISTRIBUCCION

CREATE TABLE IF NOT EXISTS hemocomponente (
  id_hemo       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ext        INTEGER NOT NULL,
  tipo          VARCHAR(40) NOT NULL,
  volumen_ml    SMALLINT,
  fecha_prep    DATE DEFAULT CURRENT_DATE,
  fecha_venc    DATE,
  estado        VARCHAR(20) DEFAULT 'DISPONIBLE',
  observacion   VARCHAR(200),
  CONSTRAINT fk_hemo_ext FOREIGN KEY (id_ext)
    REFERENCES extraccion(id_ext)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS control_calidad_hemo (
  id_cc_hemo    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_hemo       INTEGER NOT NULL,
  parametro     VARCHAR(60) NOT NULL,
  valor         VARCHAR(60),
  conforme      BOOLEAN,
  fecha_control TIMESTAMP DEFAULT now(),
  observacion   VARCHAR(200),
  CONSTRAINT fk_cc_hemo FOREIGN KEY (id_hemo)
    REFERENCES hemocomponente(id_hemo)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS destino (
  id_destino    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(120) NOT NULL,
  direccion     VARCHAR(200),
  telefono      VARCHAR(30),
  responsable   VARCHAR(120),
  activo        BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS pedido (
  id_pedido     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_destino    INTEGER NOT NULL,
  fecha_solic   TIMESTAMP DEFAULT now(),
  estado        VARCHAR(20) DEFAULT 'PENDIENTE',
  observacion   VARCHAR(200),
  CONSTRAINT fk_pedido_destino FOREIGN KEY (id_destino)
    REFERENCES destino(id_destino)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS detalle_pedido (
  id_pedido     INTEGER NOT NULL,
  id_hemo       INTEGER NOT NULL,
  cantidad      INTEGER DEFAULT 1,
  PRIMARY KEY (id_pedido, id_hemo),
  CONSTRAINT fk_det_pedido FOREIGN KEY (id_pedido)
    REFERENCES pedido(id_pedido)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_det_hemo FOREIGN KEY (id_hemo)
    REFERENCES hemocomponente(id_hemo)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS entrega (
  id_entrega    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido     INTEGER NOT NULL,
  recibido_por  VARCHAR(120),
  fecha_entrega TIMESTAMP DEFAULT now(),
  observacion   VARCHAR(200),
  estado        VARCHAR(20) DEFAULT 'ENTREGADO',
  CONSTRAINT fk_entrega_pedido FOREIGN KEY (id_pedido)
    REFERENCES pedido(id_pedido)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS distribucion_log (
  id_log        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_entrega    INTEGER NOT NULL,
  id_hemo       INTEGER NOT NULL,
  estado_anterior VARCHAR(20),
  estado_nuevo    VARCHAR(20),
  fecha_evento    TIMESTAMP DEFAULT now(),
  usuario_reg     VARCHAR(60),
  CONSTRAINT fk_log_entrega FOREIGN KEY (id_entrega)
    REFERENCES entrega(id_entrega)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_log_hemo FOREIGN KEY (id_hemo)
    REFERENCES hemocomponente(id_hemo)
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_hemo_ext           ON hemocomponente(id_ext);
CREATE INDEX IF NOT EXISTS ix_hemo_estado        ON hemocomponente(estado);
CREATE INDEX IF NOT EXISTS ix_pedido_destino     ON pedido(id_destino);
CREATE INDEX IF NOT EXISTS ix_det_pedido_hemo    ON detalle_pedido(id_hemo);
CREATE INDEX IF NOT EXISTS ix_entrega_pedido     ON entrega(id_pedido);
CREATE INDEX IF NOT EXISTS ix_log_hemo_estado    ON distribucion_log(id_hemo, estado_nuevo);

-- Data Seeding (Minimal) to avoid login errors
-- Assuming role 'ADMIN' and user 'admin'
INSERT INTO rol (nombre, descripcion) VALUES ('ADMIN', 'Administrador del sistema');
INSERT INTO personal (nom, ape_pat, ape_mat, ci, profesion, ocupacion, sexo, email) 
VALUES ('System', 'Admin', 'User', '0000000', 'Ingeniero', 'Admin', 'M', 'admin@bloodbank.com');

-- Password 'admin' hashed (Placeholer, needs correct hash)
-- For now, inserting a dummy user. Real auth might fail if hash logic is specific.
INSERT INTO usuario (id_pers, login, pass_hash) 
VALUES (1, 'admin', 'NOT_A_REAL_HASH'); 

INSERT INTO usuario_rol (id_usr, id_rol) VALUES (1, 1);
