package org.apache.jsp.analisis;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modificar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>Resultados</title>\n");
      out.write("   <style type=\"text/css\" media=\"screen\">\n");
      out.write("       @import url( style.css );\n");
      out.write("   </style>  \n");
      out.write("  <script src='validaciones.js'></script>\n");
      out.write("  <script src='modificar.js'></script>\n");
      out.write(" \n");
      out.write("  <script src='/mili1/dwr/interface/ListaHemaDAO.js'></script>\n");
      out.write("  \n");
      out.write("  <script src='/mili1/dwr/interface/BusquedaDAO.js'></script>\n");
      out.write("  <SCRIPT language='JavaScript' src=\"../scripts/overlib_mini.js\"></SCRIPT>\n");
      out.write("  <script src='/mili1/dwr/engine.js'></script>\n");
      out.write("  <script src='/mili1/dwr/util.js'></script>\n");
      out.write("</head>\n");
      out.write("<body onload='ListaCod_per();' >  \n");
      out.write("\n");
      out.write("    <input  id=\"id_horario\" type=\"hidden\">\n");
      out.write("    <input  id=\"cod_per\" type=\"hidden\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <input type='hidden' id='total'>\n");
      out.write("    <input type='hidden' id='apepa8'>\n");
      out.write("    <input type='hidden' id='apema8'>\n");
      out.write("    <input type='hidden' id='nom8'>\n");
      out.write("\n");
      out.write("<!-- inicio busqueda : por ci,cod_do y apepa-->\n");
      out.write("<table class='tabla' style='display' id='busqueda'>\n");
      out.write("    <caption class='trCaption'><h3>Busqueda de Donantes<input type='image' src='../imagenes/progress.gif' ></input></h3></caption>\n");
      out.write("    <tr class='trFilas'>\n");
      out.write("\t<td align=\"right\">Codigo::..</td>\n");
      out.write("\t<td align=\"center\"><input type='text' name='cod_do'  id='cod_do' size='15' maxlength='9'></td>\n");
      out.write("        <td align=\"center\"><span id='EmC'></span></td>         \n");
      out.write("\t<td align=\"left\"><input type='image' src='../imagenes/david.png'  onclick='BusquedaCodigo();'></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr class='trFilas'>\n");
      out.write("\t<td align=\"right\">Nro de CI::..</td>\n");
      out.write("\t<td align=\"center\"><input type='text' name='ci' size='15' maxlength='7' id='ci'></td>\n");
      out.write("        <td align=\"center\"><span id='EmCi'></span></td>\n");
      out.write("\t<td align=\"left\"><input type='image' src='../imagenes/david.png'  onclick='BusquedaCi();'></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr class='trFilas'>\n");
      out.write("\t<td align=\"right\">Apellido Paterno::..</td>\n");
      out.write("\t<td align=\"center\"><input type='text'  size='15' maxlength='10' id='apepa1'></td>\n");
      out.write("        <td align=\"center\"><span id='EmA'></span></td>    \n");
      out.write("\t<td align=\"left\"><input type='image' src='../imagenes/david.png'  onclick='BusquedaApellido();'></td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<!-- fin busqueda : por ci,cod_do y apepa-->\n");
      out.write("\n");
      out.write("<!/////////INICIO BUSQUEDA POR APELLIDO>\n");
      out.write("<div style='display:none' id='resultado_apellido'>\n");
      out.write("    <table class='tabla' id='hola' >\n");
      out.write("          <caption class='trCaption'><H3>Informacion del Donante</H3></caption>\n");
      out.write("          <BR>\n");
      out.write("          <thead>\n");
      out.write("          <tr class='trFilas'>\n");
      out.write("               <th>Codigo</th>\n");
      out.write("               <th>Nombre</th>\n");
      out.write("               <th>A.Paterno</th>\n");
      out.write("               <th>A.Materno</th>\n");
      out.write("\t       <th>Ingresar</th>\n");
      out.write("          </tr>\n");
      out.write("          </thead>\n");
      out.write("\t            <tbody id='campos_de_apellido' align='center'></tbody>\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("<!/////////FIN DE BUSQUEDA POR APELLIDO>\n");
      out.write("<!/////////modificacion>\n");
      out.write("<div style='display:none' id='modi'>    \n");
      out.write("<table class='tabla'>\n");
      out.write("<caption class='trCaption'><h3>Modificar Inmunohematologia</h3></caption>\n");
      out.write("<tr class='trFilas'>\n");
      out.write("<th align=\"right\">Donante::.</th>\n");
      out.write("<td><span id='nom'></span> - <span id='apepa'></span> - <span id='apema'></span>\n");
      out.write("</td>\n");
      out.write("<th align=\"right\">Codigo::.</td>\n");
      out.write("<td><span id='codigo_donante'></span></td>\n");
      out.write("</tr>\n");
      out.write("<tr class='trFilas'>\n");
      out.write("   <TH align=\"right\">Fecha Extraccion::. </TH>\n");
      out.write("   <TD> <FORM name='caja'  method='post' doubleClick='validarFechae();' onBlur='validarFechae2();'>\n");
      out.write("    <span id='overDiv' style=\"Z-INDEX: 1000; VISIBILITY: hidden; POSITION: absolute\"></span>\n");
      out.write("    <input  id='fecha_prueba' readonly='true' size='15'>\n");
      out.write("    <A onmouseout=\"window.status=''; nd(); return true;\" href=\"javascript:show_calendar('caja.fecha_prueba');\"><IMG src=\"../imagenes/caldrbtn.gif\"  border=0></A>\n");
      out.write("    </FORM> </TD>\n");
      out.write("\n");
      out.write("<th align=\"right\">Hora::.</th>\n");
      out.write("<td><span  id='hora_prueba' ></span></td><td></td><td></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<table class='tabla'>\n");
      out.write("<thead>\n");
      out.write("<tr class='trFilas'>\n");
      out.write("<th>Nro</th>\n");
      out.write("<th>Prueba</th>\n");
      out.write("<th>Codigo</th>\n");
      out.write("<th>Resultado</th>\n");
      out.write("<th></th>\n");
      out.write("</tr>\n");
      out.write("</thead>\n");
      out.write("<tbody id='camposp' align='center'>\n");
      out.write("<th><span id='EmV'></span></th>\n");
      out.write("</tbody>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<table class='tabla'>\n");
      out.write("<tr class='trFilas'>\n");
      out.write(" <td colspan=\"3\"  align='center' >\n");
      out.write(" <input type='image' src='../imagenes/modificar.png' onclick='InsertarC();'></td>\n");
      out.write(" <td align='center'>\n");
      out.write(" <input type='image' src='../imagenes/cancelar1.png' onclick='ejecutarCero();'></td> \n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<input type='hidden' id='bb'>\n");
      out.write("<input type='hidden' id='id_aten'>\n");
      out.write("<input type='hidden' id='cod_do'>\n");
      out.write("<input type='hidden' id='tipo_componente'>\n");
      out.write("<input type='hidden' id='id_pruebaF'>\n");
      out.write("<input type='hidden' id='resultado'>\n");
      out.write("<input type='hidden' id='d'>\n");
      out.write("</div>\n");
      out.write("<!/////////prueb a div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!/////////INICIO BUSQUEDA POR APELLIDO>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!/////INICIO BUSQUEDA POR CI Y CODIGO////////////>\n");
      out.write("<div style='display:none' id='resultado_todo'>\n");
      out.write("    <table class='tabla'>\n");
      out.write("        <caption class='trCaption'><H3>Informacion del Donante</H3></caption>\n");
      out.write("        <BR>\n");
      out.write("        <thead>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("             <th>Codigo</th>\n");
      out.write("             <th>A.Paterno</th>\n");
      out.write("             <th>A.Materno</th>\n");
      out.write("             <th>Nombre</th>\n");
      out.write("             <th>Gs_rh</th>\n");
      out.write("        </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody id='campostodos' align='center'></tbody>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <PRE></PRE>\n");
      out.write("    <table class='tabla'>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("            <td align='center'><input type='image' src='../imagenes/ingrese_a_modificar.png' onclick='Modificar();'></td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("<!/////FIN BUSQUEDA POR CI Y CODIGO////////////>\n");
      out.write("\n");
      out.write("<!-- **********************************************-->\n");
      out.write("<!-- *************inicio de modificar*********************************-->\n");
      out.write("<div style='display:none' id='resultado_donacion'>\n");
      out.write("    <table class='tabla'>\n");
      out.write("        <caption class='trCaption'>Adicionar  Donacion</caption>\n");
      out.write("        <BR>\n");
      out.write("        <thead>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("             <th></th>\n");
      out.write("             <th>Codigo</th>\n");
      out.write("             <th>A.Paterno</th>\n");
      out.write("             <th>A.Materno</th>\n");
      out.write("             <th>Nombre</th>\n");
      out.write("             <th>Gs_rh</th>\n");
      out.write("             <th>Ci</th>\n");
      out.write("             <th>Profesion</th>\n");
      out.write("             <th>Ocupacion</th>\n");
      out.write("        </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody id='campos_1'></tbody>\n");
      out.write("    </table>\n");
      out.write("    <table class='tabla'>\n");
      out.write("        <thead>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("            <th>Lugar Trabajo</th>\n");
      out.write("            <th>Email</th>\n");
      out.write("            <th>Fono Propio</th>\n");
      out.write("            <th>Celular</th>\n");
      out.write("            <th>Fono Vecino</th>\n");
      out.write("            <th>Fono Trabajo</th>\n");
      out.write("        <!--/tr-->\n");
      out.write("        </thead>\n");
      out.write("        <tbody id='campos_2'></tbody>\n");
      out.write("    </table>\n");
      out.write("    <table class='tabla'>\n");
      out.write("        <thead>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("            <th>Calle/Residencia</th>\n");
      out.write("            <th>Nro</th>\n");
      out.write("            <th>Zona</th>\n");
      out.write("            <th>Domicilio</th>\n");
      out.write("        <!--/tr-->\n");
      out.write("        </thead>\n");
      out.write("        <tbody id='campos_3'></tbody>\n");
      out.write("        <thead>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("            <th>Calle/Residencia</th>\n");
      out.write("            <th>Nro</th>\n");
      out.write("            <th>Zona</th>\n");
      out.write("            <th>Domicilio1</th>\n");
      out.write("        <!--/tr-->\n");
      out.write("        </thead>\n");
      out.write("        <tbody id='campos_4'></tbody>\n");
      out.write("        <PRE></PRE>\n");
      out.write("        <tr class='trFilas'>\n");
      out.write("            <td><input type=\"submit\" value=\"Aceptar\" onclick='modificar_valor();'></td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("<!-- *************fin de modificar************************************-->\n");
      out.write("\n");
      out.write("<!-- *************************************************-->\n");
      out.write("<table class='tabla' style='display:none' id='mensaje'>\n");
      out.write("<tr class='trFilas'>\n");
      out.write("<td>\n");
      out.write("Datos insertados Correctamente!--------------\n");
      out.write("<input type=\"submit\" value=\"Siquiente\" onclick='visualizar();'>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<!-- ****************************************************-->\n");
      out.write("\n");
      out.write("<!-- ***************inicio examen fisico********************************-->\n");
      out.write("<div style='display:none' id='examenFisico'>\n");
      out.write("    <table class='tabla'>\n");
      out.write("\t<caption class='trCaption'><h4>Examen Fisico</h4></caption>\n");
      out.write("\t    <input type=\"hidden\" id='atendido' value=\"T\">\n");
      out.write("\t    <input type=\"hidden\" id='atendidop' value=\"T\">\n");
      out.write("\t    <input type=\"hidden\" id='atendidoh' value=\"T\">\n");
      out.write("\t    <input type=\"hidden\" id='atendidos' value=\"T\">\n");
      out.write("\t    <input type=\"hidden\" id='atendidoe' value=\"T\">\n");
      out.write("\t\t<tr class='trFilas'>\n");
      out.write("\t\t    <table class='tabla'>\n");
      out.write("\t\t    \t<tr class='trFilas'>\n");
      out.write("\t\t\t    <td>Fecha:</td>\n");
      out.write("\t\t\t    <td>\n");
      out.write("\t\t\t\t<FORM name='caja'  method='post' doubleClick='validarFechae();' onBlur='validarFechae2();'>\n");
      out.write("                        \t    <span id='overDiv' style=\"Z-INDEX: 1000; VISIBILITY: hidden; POSITION: absolute\"></span>\n");
      out.write("                        \t    <input name='fecha_a' id='fecha_a' readonly='true' size='10'>\n");
      out.write("                    \t\t    <A onmouseout=\"window.status=''; nd(); return true;\" href=\"javascript:show_calendar('caja.fecha_a');\"><IMG src=\"../imagenes/caldrbtn.gif\"  border=0></A>\n");
      out.write("                \t\t</FORM>\n");
      out.write("\t        \t\t<span id='EmFechae'></span>\n");
      out.write("\t\t\t    </td>\n");
      out.write("\t\t\t    <td>Hora.:</td>\n");
      out.write("\t    \t\t    <td><span  id='hora_a' ></span><input type='HIDDEN' id='hora_a'></td>\n");
      out.write("\t\t\t    <td>Nro:</td>\n");
      out.write("\t\t\t    <td><span  id='id_aten' ></span><input type='HIDDEN' id='id_aten'></td>\n");
      out.write("\t    \t\t</tr>\n");
      out.write("\t           </table>\n");
      out.write("\t       </tr>\n");
      out.write("\t       <tr class='trFilas'>\n");
      out.write("\t         <table class='tabla'>\n");
      out.write("\t            <td>Tipo de Donacion:</td>\n");
      out.write("\t            <td><select id='tipo_do'  onblur='validarCombos111();'>         \n");
      out.write("\t\t\t  <option value=\"V\" align='center'>Voluntaria</option>\n");
      out.write("\t\t          <option value=\"R\" align='center'>Reposicion/Familiar</option>\n");
      out.write("\t\t          <option value=\"A\" align='center'>Autóloga</option>\n");
      out.write("\t\t\t  <option value=\"-1\" selected='selected'>---Seleccione---</option>\n");
      out.write("\t\t       </select>\n");
      out.write("\t              <span id='EmCom'></span></td>\n");
      out.write("\t           <td><select id='veces' onblur='validarCombos112();'>\n");
      out.write("\t\t          <option value=\"H\" align='center'>Habitual</option>\n");
      out.write("\t\t          <option value=\"P\" align='center'>Primera_Vez</option>\n");
      out.write("\t\t\t  <option value=\"-1\" selected='selected'>---Seleccione---</option>\n");
      out.write("\t               </select>\n");
      out.write("\t\t <span id='EmComb'></span></td>\n");
      out.write("\t       </table>\n");
      out.write("\t      </tr> \n");
      out.write("\t     <tr align='center' class='trFilas'>\n");
      out.write("\t\t<table class='tabla'>\n");
      out.write("\t\t    <tr class='trFilas'><td>Tension_Arterial:</td></tr>\n");
      out.write("\t\t    <tr class='trFilas'><td>Sistólica</td>\n");
      out.write("\t\t\t<td><input id='sistolica'  size=\"8\"  onBlur='validarEntero111();'>\n");
      out.write("\t        \t<span id='EmSi'></span></td>\n");
      out.write("\t\t\t<td>Diastólica</td>\n");
      out.write("\t\t\t<td><input id='diastolica'  size=\"8\" onBlur='validarEntero112();'>\n");
      out.write("\t\t            <span id='EmDi'></span>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t    </tr>\n");
      out.write("\t\t    <tr class='trFilas'><td>Pulso</td>\n");
      out.write("\t    \t\t<td><input id='pulso' size=\"8\"  onBlur='validarEntero113();'>\n");
      out.write("\t    \t\t<span id='EmPu'></span>\n");
      out.write("\t\t\tpul./min.</td>\n");
      out.write("\t\t\t<td>Peso</td>\n");
      out.write("\t\t\t<td><input id='peso'  size=\"8\" onBlur='validarEntero114();'>\n");
      out.write("\t    \t\t    <span id='EmPe'></span>\n");
      out.write("\t\t\tKg.</td></tr>\n");
      out.write("\t\t    <tr class='trFilas'>\n");
      out.write("\t\t\t<td>Talla</td>\n");
      out.write("\t\t\t<td><input id='talla' size=\"8\" onBlur='validarEntero115();'>\n");
      out.write("\t    \t\t<span id='EmTa'></span>\n");
      out.write("\t\t\tcms.</td>\n");
      out.write("\t\t\t<td>Temperatura</td>\n");
      out.write("\t\t\t<td><input id='temperatura' size=\"8\" onBlur='validarEntero116();'>\n");
      out.write("\t    \t\t<span id='EmTe'></span>\n");
      out.write("\t\t\t°C</td>\n");
      out.write("\t\t     </tr>\n");
      out.write("\t\t     <tr class='trFilas'>\n");
      out.write("\t\t\t<td colspan=\"3\" align=\"center\"><div id='agregar12'></div></td>\n");
      out.write("\t\t\t<td><input type=\"submit\" value=\"Cancelar\" onclick='ejecutarCero();'></td>\n");
      out.write("\t\t     </tr>\n");
      out.write("\t\t     \n");
      out.write("\t\t</table>\n");
      out.write("\t\t</tr>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- *****************fin examen fisico********************************-->\n");
      out.write("<!-- *****************inicio MENSAJE examen fisico********************************-->\n");
      out.write("<table class='tabla' style='display:none' id='adios'>\n");
      out.write("<caption class='trCaption'>\n");
      out.write("<font color=\"blue\" size='3'>Datos modificados correctamente!--------------</font>\n");
      out.write("</caption>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("<!-- *****************fin MENSAJE examen fisico********************************-->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
